#
# SystemWrapper solution
# AppVeyor configuration
#

version: 0.9.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

platform: Any CPU
configuration: Release

before_build:
  nuget restore

build:
  project: SystemWrapper.sln
  verbosity: detailed

assembly_info:
  patch: true
  file: 'Build\AssemblySharedInfo.cs'
  assembly_version: "{version}"
  assembly_file_version: "1.0.0.0"
  assembly_informational_version: "{version}"

test:
  assemblies:
    - SystemWrapper.Tests.dll

cache:
  - packages
